# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Angus Innes
email: a.innes9@gmail.com
description: Hi. I'm a full stack developer and I want to aid entrepreneurs realize their goals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trackuh.tumblr.com" # the base hostname & protocol for your site
twitter_username: xberutix
github_username:  beruti

# Build settings
markdown: kramdown
